### ISSUE TITLE
ICP tracking error

### ISSUE THREAD

**Issue by antonyvan** [JingwenWang95/KinectFusion#2]
Hello,
Thanks a lot for your sharing your code.  I have tried to run the default sample kinfu.py with  configs/fr1_desk.yaml.  It runs well with  img_scale=0.25 (for     dataset = TUMDataset(os.path.join(args.data_root), device, near=args.near, far=args.far, img_scale=0.25)
). ![Figure_1](https://user-images.githubusercontent.com/40614822/220290217-2a13f29b-d585-4416-a507-903f23b5321b.png)

 However, if I change img_scale = 0.5. the tracking becomes very bad.![Figure_2](https://user-images.githubusercontent.com/40614822/220290100-a6096f2b-be1e-43fd-9c9e-9022b9782e5f.png)

If I change img_scale to 1.0, ICP produce errors. 
![Screenshot from 2023-02-21 00-08-24](https://user-images.githubusercontent.com/40614822/220290324-4dbdbca3-eae4-4ebf-b2c6-543a356d580a.png)

Could you help me out this problem? 
Thanks 
Regards

**Comment by JingwenWang95** [comment]
Hi @antonyvan, thanks for your interests for this project. I tuned all the parameters with default resolution (img_scale=0.25), so you might need to do some parameter tuning if you want to use higher resolution. And even for the default resolution I didn't spent much time tuning those parameters, so it might be that those parameters are not optimal for running ICP. And for the ICP error, it says that the Hessian matrix is not invertible, which also manifests that the optimisation problem becomes unstable. So I would suggest that you do some further parameter tuning.

**Comment by antonyvan** [comment]
Thanks, Jingwen,
Appreciate your feedback and work. I will take a look at registration.   Regards
________________________________

**Comment by RollRoll520** [comment]
@antonyvan 
Hello, I have also encountered this situation. I made an error when using my own dataset. Have you solved this problem?
![image](https://github.com/JingwenWang95/KinectFusion/assets/96854955/7cc7b7b3-eec7-4a51-87d1-7ebca04af34f)

**Comment by antonyvan** [comment]
unfortunately, I didn't solve the issue. :(

**Comment by Langwenchong** [comment]
Hello, have you resolved this issue? After debugging the code, I found that the error is mainly due to the elements on the main diagonal of the Hessian matrix gradually becoming zero during the optimization process. Since the Hessian matrix is primarily computed from the Jacobian matrix through multiplication, the problem likely originates from the Jacobian matrix during the iterative optimization. Do you have any further thoughts on this?
